# Generated by Django 4.0.6 on 2023-09-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.URLField(blank=True, help_text='Avatar URL', verbose_name='Avatar'),
        ),
    ]
