# Generated by Django 4.0.6 on 2023-09-02 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('checkin', models.DateTimeField(blank=True, null=True, verbose_name='Checkin')),
                ('service', models.IntegerField(choices=[(1, 'Manutenção corretiva'), (2, 'Manutenção preventiva'), (3, 'Calibração')], default=1, verbose_name='Tipo de serviço')),
                ('request_description', models.TextField(blank=True, verbose_name='Descrição')),
                ('job_description', models.TextField(blank=True, help_text='Útil para inspeção futura', verbose_name='Solução')),
                ('status', models.IntegerField(choices=[(1, 'Aberto'), (2, 'Em atendimento'), (3, 'Finalizado')], default=1, verbose_name='Status')),
                ('checkout', models.DateTimeField(blank=True, null=True, verbose_name='Checkout')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_works', to='equipments.equipment', verbose_name='Equipamento')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='requester_orders', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='worker_orders', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador')),
            ],
        ),
    ]
