# Generated by Django 4.0.6 on 2023-09-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='service',
            field=models.IntegerField(choices=[(1, 'Manutenção corretiva'), (2, 'Manutenção preventiva'), (3, 'Calibração'), (4, 'Treinamento'), (5, 'Instalação')], default=1, verbose_name='Tipo de serviço'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.IntegerField(choices=[(1, 'Aberto'), (2, 'Em atendimento'), (3, 'Finalizado'), (4, 'Impossível realizar')], default=1, verbose_name='Status'),
        ),
    ]
