# Generated by Django 4.0.6 on 2023-09-02 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('name', models.CharField(max_length=75, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, max_length=75, null=True, verbose_name='Descrição')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado em')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('name', models.CharField(max_length=75, unique=True, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado em')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('name', models.CharField(max_length=75, unique=True, verbose_name='Nome')),
                ('operating_instructions', models.FileField(blank=True, upload_to='equipment_model_upload_to', verbose_name='Instruções de operação')),
                ('image_1', models.ImageField(blank=True, upload_to='equipment_model_upload_to', verbose_name='Foto 1')),
                ('image_2', models.ImageField(blank=True, upload_to='equipment_model_upload_to', verbose_name='Foto 2')),
                ('image_3', models.ImageField(blank=True, upload_to='equipment_model_upload_to', verbose_name='Foto 3')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado em')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_equipments', to='equipments.equipmenttype', verbose_name='Tipo de equipamento')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_equipments', to='equipments.manufacturer', verbose_name='Fabricante')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('year_of_manufacture', models.PositiveSmallIntegerField(default=2010, verbose_name='Ano de fabricação')),
                ('serial_number', models.CharField(max_length=75, unique=True, verbose_name='Número de série')),
                ('patrimony', models.CharField(max_length=75, unique=True, verbose_name='Número de patrimônio')),
                ('accident_history', models.BooleanField(default=True, verbose_name='Histórico de acidente')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado em')),
                ('work_priority', models.PositiveSmallIntegerField(choices=[(1, 'Baixo'), (2, 'Medio'), (3, 'Alto'), (4, 'Urgente')], default=1, verbose_name='Prioridade')),
                ('qr_code', models.ImageField(blank=True, upload_to='equipments/qr_code', verbose_name='QR Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('equipment_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_equipments', to='equipments.equipmentmodel', verbose_name='Modelo do equipamento')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.location', verbose_name='Localização')),
            ],
        ),
    ]
