# Generated by Django 4.0.6 on 2023-09-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='mean_failure_time',
            field=models.PositiveSmallIntegerField(default=2010, verbose_name='Tempo médio de falha (meses)'),
        ),
    ]
