# Generated by Django 4.0.6 on 2023-09-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_equipmenttype_mean_failure_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de aquisição'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='external_maintenance',
            field=models.BooleanField(default=False, verbose_name='Manutenção externa'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='warranty_expiration',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimento da garantia'),
        ),
    ]
